version: '3'
services:
  decidim:
    image: decidim/decidim:0.8-dev
    entrypoint: []
    command: decidim
    working_dir: "/code"
    ports:
      - "3000:3000"
    volumes:
      - .:/code
      - bundle:/usr/local/bundle
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
    links:
      - pg
      - redis
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  dummy_app: {}
  bundle: {}
  pg-data: {}
  redis-data: {}
